Integración de últimos cambios hechos al Front-end
marceg88/MyLittleFriend pull request #18
Opened 2022-01-31 04:11 UTC by Kasuk1

Hola Mateo, el siguiente PR es un cambio relevante en temas de diseño de la app. Somos conscientes de algunas importaciones de ant-design que hemos dejado flotando, sin embargo por ahora vemos conveniente dejarlas allí por el momento.

2022-01-31 16:28 UTC, mhbuiles requested changes
No deberíamos subir imágenes a los repositorios

2022-01-31 16:28 UTC, mhbuiles commented on src/components/globales/footer/Footer.css
> +}
Se recomienda dejar una línea en blanco al final de cada archivo

2022-01-31 16:28 UTC, mhbuiles commented on src/components/globales/navbar/Navbar.css
> +
No es necesario dejar tantas líneas en blanco

2022-01-31 16:28 UTC, mhbuiles commented on src/components/globales/navbar/Navbar.js
> +
Esta línea en blanco no la necesitamos

2022-01-31 16:28 UTC, mhbuiles commented on src/components/globales/navbar/Navbar.js
> +};
Se recomienda dejar una línea en blanco al final de cada archivo

2022-01-31 16:28 UTC, mhbuiles commented on src/components/home/general/HomeGeneral.css
> +
No dejemos tantas líneas en blanco entre bloques de código

2022-01-31 16:28 UTC, mhbuiles commented on src/components/home/general/HomeGeneral.js
> +                            alt=''
Es bueno que agreguemos un string a este atributo, esto ayudará a mejorar la accesibilidad de la aplicación para personas que utilicen lectores de pantalla.

2022-01-31 16:28 UTC, mhbuiles commented on src/components/home/usuario/HomeUsuario.js
> +export const HomeUsuario = () => {
Por qué tenemos este componente vacío?

2022-01-31 16:28 UTC, mhbuiles commented on src/components/login/formularios/LoginFormulario.css
> +@media only screen and (min-width: 37.5em)  */
Por que no borramos este comentario?

2022-01-31 16:28 UTC, mhbuiles commented on src/components/login/formularios/LoginFormulario.js
> +        console.log('Received values of form: ', values);
No dejemos console.log en el código

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/detalleMascota/MascotaDetalle.js
> +    const { name, description, image, historial } = mascotas.find(mascota => mascota.id === Number(petId));
Esto es provisional mientras traemos esta data del servidor??

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/detalleMascota/MascotaDetalleModal.css
> +.modal--info {
Necesitamos estas clases vacías? A esto hacían referencia con su comentario inicial?

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/detalleMascota/MascotaDetalleModal.js
> +            onOk() { },
No debemos pasarla algo a onOk?

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/listaMascotas/MascotaLista.css
> +.section__pets--title {
Aquí veo más clases vacías

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/listaMascotas/MascotaLista.js
> +                    {mascotas.map(mascota => <Mascota key={mascota.id} {...mascota} />)}
Esto es provisional mientras conectamos con el servidor??

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/mascota/Mascota.css
> +
Clases vacías

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/mascota/Mascota.js
> +
No dejemos tantas líneas en blanco innecesarias

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/registroMascotas/MascotaRegistro.js
> +    console.log(values);
No dejemos console.log, ya a estas alturas del bootcamp tenemos que ir completando los flujos, qué se va a hacer al enviar el formulario?

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/registroMascotas/MascotaRegistro.js
> +    console.log('Failed:', errorInfo);
Ya estas funciones deben hacer lo que les corresponde, no dejemos console.log

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/registroMascotas/MascotaRegistro.js
> +    console.log('Upload event:', e);
No console.log

2022-01-31 16:28 UTC, mhbuiles commented on src/components/mascotas/registroMascotas/MascotaRegistro.js
> +
Estas líneas en blanco no son necesarias

2022-01-31 16:28 UTC, mhbuiles commented on src/components/registro/formularios/RegistroFormulario.js
> +        console.log('Success:', values);
No dejemos console.log, ya a estas alturas del bootcamp tenemos que ir completando los flujos, qué se va a hacer al enviar el formulario?

2022-01-31 16:28 UTC, mhbuiles commented on src/components/registro/formularios/RegistroFormulario.js
> +        console.log('Failed:', errorInfo);
No dejemos console.log, ya a estas alturas del bootcamp tenemos que ir completando los flujos, qué se va a hacer al enviar el formulario? Ya tenemos que conectarnos con nuestro servidor

2022-01-31 16:28 UTC, mhbuiles commented on src/components/registro/formularios/RegistroFormulario.js
> +        console.log('Upload event:', e);
No console.log

2022-01-31 16:28 UTC, mhbuiles commented on src/components/servicios/detalleServicio/ServicioDetalle.js
> +export const ServicioDetalle = () => {
Por qué creamos componentes vacíos? Mejor los agregamos a los commit cuando ya hagan algo

2022-01-31 16:28 UTC, mhbuiles commented on src/components/servicios/listaServicios/ServiciosLista.js
> +                    {servicios.map(servicio => <Servicio key={servicio.id} {...servicio} />)}
Ya debemos ir conectando al servidor.

2022-01-31 16:28 UTC, mhbuiles commented on src/components/servicios/solicitudServicio/ServicioSolicitud.js
> +    console.log("formulario enviado", datos);
Estos endpoints ya están listos en el backend? Si es así, debemos ir conectando

2022-01-31 16:28 UTC, mhbuiles commented on src/components/servicios/solicitudServicio/ServicioSolicitud.js
> +    console.log("error", error);
No console.log

2022-01-31 16:28 UTC, mhbuiles commented on src/components/servicios/solicitudServicio/ServicioSolicitud.js
> +
No dejemos esta cantidad de líneas en blanco

2022-01-31 16:28 UTC, mhbuiles commented on src/components/veterinarias/listaVeterinarias/VeterinariasLista.js
> +          {veterinarias.map((veterinaria) => <Veterinaria key={veterinaria.id} {...veterinaria} />)}
Esta data va a venir de la base de datos??

2022-01-31 16:28 UTC, mhbuiles commented on src/routes/AppRoutes.js
> +
No dejemos estas líneas en blanco, se ve un poco desorganizado

2022-01-31 16:28 UTC, mhbuiles commented on src/routes/AppRoutes.js
> +                        <PublicRoutes>
Habría forma de dejar todas las rutas públicas anidadas dentro de una sola etiqueta PublicRoutes?

2022-01-31 16:28 UTC, mhbuiles commented on src/services/MyLittleFriendAPI/MyLittleFriendAPI.js
> +        console.log(token)
No console.log

2022-01-31 16:28 UTC, mhbuiles commented on src/services/MyLittleFriendAPI/MyLittleFriendAPI.js
> +const MLFURI = 'https://mylittlefriend.herokuapp.com';
Esto debe ir en las variables de entorno y ese archivo no se debe subir al repo, no debe estar ese tipo de información en el código

2022-01-31 16:28 UTC, mhbuiles commented on src/store/uiSlice/ui.slice.js
> +
No debe haber un initialstate?

2022-01-31 16:28 UTC, mhbuiles commented on src/store/userSlice/user.slice.js
> +
Por qué user es vacío? Qué pasa si iniciamos con null?

2022-01-31 16:28 UTC, mhbuiles commented on src/store/userSlice/user.slice.js
> +                    console.log(action.payload)
No console.log

2022-01-31 18:34 UTC, Kasuk1 commented on src/components/mascotas/detalleMascota/MascotaDetalle.js
> +    const { name, description, image, historial } = mascotas.find(mascota => mascota.id === Number(petId));
Hola Mateo, eso es provisional por el momento hasta q utilizemos la API.

2022-01-31 18:35 UTC, Kasuk1 commented on src/components/mascotas/detalleMascota/MascotaDetalleModal.css
> +.modal--info {
Olvidé borrarlas. Respecto al comentario inicial resulta invalidado debido a que el despliegue a Netlify me obligó a quedarme sin warnings.

2022-01-31 18:38 UTC, Kasuk1 commented on src/components/mascotas/detalleMascota/MascotaDetalleModal.js
> +            onOk() { },
Realmente solo es para ver el detalle del servicio de la mascota. Sin embargo acabo de revisar y no es un método necesario si no se realizará alguna acción al dar ok. Ya lo borré. Gracias.

2022-01-31 18:38 UTC, Kasuk1 commented on src/components/mascotas/listaMascotas/MascotaLista.js
> +                    {mascotas.map(mascota => <Mascota key={mascota.id} {...mascota} />)}
Eso es provisional.

2022-01-31 18:39 UTC, Kasuk1 commented on src/components/mascotas/registroMascotas/MascotaRegistro.js
> +    console.log(values);
Es provisional. Justo ya empezamos a integrarlo

2022-01-31 18:40 UTC, Kasuk1 commented on src/components/mascotas/registroMascotas/MascotaRegistro.js
> +    console.log('Failed:', errorInfo);
Se procederá a borrar los console.log cuando se integre a la API

2022-01-31 18:44 UTC, Kasuk1 commented on src/components/veterinarias/listaVeterinarias/VeterinariasLista.js
> +          {veterinarias.map((veterinaria) => <Veterinaria key={veterinaria.id} {...veterinaria} />)}
No está planeado debido a que ya tenemos un CRUD. Sin embargo, está por decidirse sea o no en duro.

2022-01-31 18:47 UTC, Kasuk1 commented on src/routes/AppRoutes.js
> +                        <PublicRoutes>
Si se puede, sin embargo nos evitamos importar componentes a public o private, y solo dejamos la lógica definida para ambos, desestructurando sus children.

2022-01-31 18:48 UTC, Kasuk1 commented on src/store/uiSlice/ui.slice.js
> +
Aún esta por verse, ya que no hemos agregado estados que cambiaran en la ui. Sin embargo, de no necesitarlo se eliminará el slice.

2022-01-31 18:49 UTC, Kasuk1 commented on src/store/userSlice/user.slice.js
> +
Por ahora lo hemos dejado vacío porque necesitaremos del consumo de la API primero. Justo ahora trabajando en eso.

2022-01-31 18:50 UTC, Kasuk1 commented on src/store/userSlice/user.slice.js
> +                    console.log(action.payload)
Solo fue para asegurarse del response del método asincrono.

2022-01-31 18:51 UTC, Kasuk1 commented on src/store/userSlice/user.slice.js
> +                    console.log(action.payload)
Por ahora dejaremos console.log en los estados de los extraReducers. Al final ya quitaremos todos los q implementemos correctamente.

2022-02-01 15:22 UTC, mhbuiles approved these changes

2022-02-10 15:48 UTC, merged