Agrega Home Principal
marceg88/MyLittleFriend pull request #8
Opened 2021-12-03 15:21 UTC by JeanMarco173

2021-12-06 03:57 UTC, mhbuiles requested changes

2021-12-06 03:57 UTC, mhbuiles commented on src/components/home/general/HomeGeneral.jsx
> +import { Row, Col, Carousel, Card, Comment, Tooltip, List, Form, Input, Button } from 'antd';
Esto no es obligatorio, pero como sugerencia si quieren ir acostumbrándose, el orden recomendado de los import es: primero los single imports en mayúscula, luego los single import en minúscula, luego los import sin nombre y al final los múltiples import, siempre respetando el orden alfabético, y las mayúsculas, en este caso:

import moment from 'moment';
import "./homeStyles.css";
import { Row, Col, Carousel, Card, Comment, Tooltip, List, Form, Input, Button } from 'antd';
import { useState, useEffect, Fragment } from 'react'

2021-12-06 03:57 UTC, mhbuiles commented on src/components/home/general/HomeGeneral.jsx
> +const carouselUrls = [
Por favor seamos consistentes con la indentación en todo el proyecto, si vamos a usar 2 espacios, que sean 2 espacios en todos los archivos, y no 2 en unos y 4 en otros. En todo caso, se prefiere la indentación a 2 espacios.

2021-12-06 03:57 UTC, mhbuiles commented on src/components/home/general/HomeGeneral.jsx
> +const servicesArray = [
Yo recomendaría que estos arreglos grandes con tanta información, que son solo mocks, se muevan a otro archivo dentro de la misma carpeta donde está el componente HomeGeneral, y se importen para ser usados dentro de este componente.

2021-12-06 03:57 UTC, mhbuiles commented on src/components/home/general/HomeGeneral.jsx
> +    const [services, setServices] = useState();
Sería mejor inicializar el estado con un arreglo vacío, si es que "services" es un arreglo.

2021-12-06 03:57 UTC, mhbuiles commented on src/components/home/general/HomeGeneral.jsx
> +        console.log(values);
Permitiré console.log en este caso solo porque tenemos pendiente conectar los servicios del backend, debemos cambiarlos una vez se creen los servicios y tengamos las funciones que se vayan a ejecutar al enviar los formularios. De resto, no dejemos console.log en nuestro código.

2021-12-06 03:57 UTC, mhbuiles commented on src/components/home/general/HomeGeneral.jsx
> +                            <img alt="example" className="Image__Carousel" src={item}/>
No nos hace falta el prop key?

2021-12-06 03:57 UTC, mhbuiles commented on src/components/home/general/homeStyles.css
> +}
Es recomendable siempre dejar una línea en blanco al final de todos los archivos del proyecto

2021-12-07 01:50 UTC, closed without merging

2021-12-07 01:50 UTC, JeanMarco173 commented
se levanto las observaciones